<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\NamingService.Application\NamingService.Application.csproj" />
    <ProjectReference Include="..\NamingService.Infrastructure\NamingService.Infrastructure.csproj" />
  </ItemGroup>

</Project>
