<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\LinkService.Application\LinkService.Application.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Dapper" Version="2.1.35" />
    <PackageReference Include="FluentMigrator" Version="8.0.1" />
    <PackageReference Include="FluentMigrator.Runner" Version="8.0.1" />
    <PackageReference Include="FluentMigrator.Runner.Postgres" Version="8.0.1" />
    <PackageReference Include="Confluent.Kafka" Version="2.6.0" />
    <PackageReference Include="Microsoft.Extensions.Hosting.Abstractions" Version="9.0.0" />
    <PackageReference Include="Npgsql" Version="9.0.3" />
  </ItemGroup>

</Project>
