apiVersion: v1
kind: Secret
metadata:
  name: userservice-secrets
type: Opaque
stringData:
  postgres-password: "postgres"
  connection-string: "Host=postgres;Port=5432;Database=userservice;Username=postgres;Password=postgres"
